import type { Metadata } from "next";
import "../globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { ReactNode } from "react";
import { notFound } from "next/navigation";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Toaster } from "sonner";

import { routing } from "@/i18n/routing";
import { AppDialog } from "@/components/app-dialog";
import { Providers } from "@/components/providers";
import { ConfirmDialog } from "@/components/confirm-dialog";
import { AppSheet } from "@/components/app-sheet";

export const metadata: Metadata = {
  title: "CRM SomeDev",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`antialiased`}>
        <NextIntlClientProvider>
          <Providers>
            {children}
            <AppDialog />
            <ConfirmDialog />
            <Toaster />
            <AppSheet />
            <ReactQueryDevtools initialIsOpen={false} />
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
